from django.urls import path
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
    path ('', views.index, name = "index"),
    path ('about/', views.about, name = "about"),
    path ('bank/', views.bank, name = "bank"),
    path ('borrow/', views.borrow, name = "borrow"),
    path ('business_banking/', views.business_banking, name = "business_banking"),
    path ('buy_crypto/', views.buy_crypto, name = "buy_crypto"),
    path ('card_deposit/', views.card_deposit, name = "card_deposit"),
    path ('careers/', views.careers, name = "careers"),
    path ('checkings_statement/', views.checkings_statement, name = "checkings_statement"),
    path ('credit_cards/', views.credit_cards, name = "credit_cards"),
    path ('crypto_deposit/', views.crypto_deposit, name = "crypto_deposit"),
    path ('customer_support/', views.customer_support, name = "customer_support"),
    path ('faqs/', views.faqs, name = "faqs"),
    path ('giving_back/', views.giving_back, name = "giving_back"),
    path ('how_to_save_for_summer_vacation/', views.how_to_save_for_summer_vacation, name = "how_to_save_for_summer_vacation"),
    path ('insure/', views.insure, name = "insure"),
    path ('Internal_transfer/', views.Internal_transfer, name = "Internal_transfer"),
    path ('invest/', views.invest, name = "invest"),
    path ('investment/', views.investment, name = "investment"),
    path ('learn_and_plan/', views.learn_and_plan, name = "learn_and_plan"),
    path ('loan_request/', views.loan_request, name = "loan_request"),
    path ('loan/', views.loan, name = "loan"),
    path ('local_transfer/', views.local_transfer, name = "local_transfer"),
    path ('news/', views.news, name = "news"),
    path ('privacy_policy/', views.privacy_policy, name = "privacy_policy"),
    path ('profile/', views.profile, name = "profile"),
    path ('register/', views.register, name = "register"),
    path ('save/', views.save, name = "save"),
    path ('savings_statement/', views.savings_statement, name = "savings_statement"),
    path ('simple_ways_to_manage_a_checking_account/', views.simple_ways_to_manage_a_checking_account, name = "simple_ways_to_manage_a_checking_account"),
    path ('success/<str:pk>/', views.viewSuccess, name = "success"),
    path ('support/', views.support, name = "support"),
    path ('tax_checklist_5_things_to_remember/', views.tax_checklist_5_things_to_remember, name = "tax_checklist_5_things_to_remember"),
    path ('the_impact_of_rising_rates_and_inflation_on_your_business/', views.the_impact_of_rising_rates_and_inflation_on_your_business, name = "the_impact_of_rising_rates_and_inflation_on_your_business"),
    path ('user/', views.user, name = "user"),
    path ('wire_transfer/', views.wire_transfer, name = "wire_transfer"),
    path ('notifications/', views.notifications, name = "notifications"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('template_activate_account', views.template_activate_account, name='template_activate_account'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path ('logout/', views.custom_logout, name = "logout"),
    path ('check_deposit/', views.check_deposit, name = "check_deposit"),
    path ('email3/', views.email3, name = "email3"),
    path ('email4/', views.email4, name = "email4"),
    path ('pin/', views.pin, name = "pin"),
    path ('processing/', views.processing, name = "processing"),


 ]