# Generated by Django 5.1.3 on 2024-11-29 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=200, null=True)),
                ('amount', models.CharField(max_length=200, null=True)),
                ('iban_accountnumber', models.CharField(max_length=200, null=True)),
                ('accountname', models.CharField(max_length=200, null=True)),
                ('bank_name', models.CharField(max_length=200, null=True)),
                ('swift_code', models.CharField(max_length=200, null=True)),
                ('bank_address', models.CharField(max_length=200, null=True)),
                ('routing_transit_number', models.TextField(max_length=200, null=True)),
                ('time', models.DateField(auto_now=True)),
                ('purpose', models.TextField(max_length=200, null=True)),
                ('transactionid', models.CharField(default='FDG637GDJYU**', max_length=200, null=True)),
                ('status', models.CharField(choices=[('Pending...', 'Pending...'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending...', max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
