# Generated by Django 5.1.3 on 2024-11-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_alter_transfer_routing_transit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='account_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
