# Generated by Django 5.1.3 on 2024-11-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_transfer_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='account_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='accountname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='bank_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='iban_accountnumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='purpose',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='routing_transit_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending...', 'Pending...'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending...', max_length=200),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='swift_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transactionid',
            field=models.CharField(blank=True, default='FDG637GDJYU**', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
