# Generated by Django 5.1.3 on 2024-11-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0007_deposit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='account_number',
        ),
        migrations.AddField(
            model_name='deposit',
            name='chcking_account_number',
            field=models.CharField(default='Generating Account Number...', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='savings_account_number',
            field=models.CharField(default='Generating Account Number...', max_length=200, null=True),
        ),
    ]
