# Generated by Django 5.1.3 on 2024-11-29 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0008_remove_deposit_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='chcking_account_number',
            new_name='checking_account_number',
        ),
    ]
