# Generated by Django 5.1.3 on 2024-11-29 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0009_rename_chcking_account_number_deposit_checking_account_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('amount', models.CharField(default='0', max_length=200, null=True)),
                ('occupation', models.CharField(default='0', max_length=200, null=True)),
                ('purpose', models.CharField(default='', max_length=200, null=True)),
                ('status', models.CharField(default='Pending', max_length=200, null=True)),
                ('time', models.DateField(default='Pending', max_length=200, null=True)),
                ('refrence', models.CharField(default='Pending', max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
