# Generated by Django 5.1.3 on 2024-11-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0012_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='slip1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='check',
            name='slip2',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
